name: helping_hand
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.4.10
  flutter_hooks: ^0.20.5
  nanoid: ^1.0.0
  http: ^1.2.1
  stream_transform: ^2.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.9
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/default_image.jpg
